openapi: 3.0.0
info:
  title: Object Storage Service
  version: 1.0.1
  description: API for managing blobs or byte packages.

components:
  securitySchemes:
    AuthToken:
      type: http
      scheme: bearer

security:
  - AuthToken: []

paths:
  /api/v1/blob:
    post:
      summary: Create a new blob
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
      responses:
        201:
          description: Blob created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  blobId:
                    type: string
                  URL:
                    type: string
      tags:
        - blob

  /api/v1/blob/{blobId}:
    get:
      summary: Retrieve a specific blob
      parameters:
        - in: path
          name: blobId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Blob retrieved successfully
      tags:
        - blob

    delete:
      summary: Delete a blob
      parameters:
        - in: path
          name: blobId
          required: true
          schema:
            type: string
      responses:
        204:
          description: Blob deleted successfully
      tags:
        - blob

    put:
      summary: Update a blob
      parameters:
        - in: path
          name: blobId
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
      responses:
        204:
          description: Blob updated successfully
      tags:
        - blob

  /api/v1/blob/{blobId}/hash:
    get:
      summary: Retrieve hash of a blob
      parameters:
        - in: path
          name: blobId
          required: true
          schema:
            type: string
        - in: query
          name: type
          schema:
            type: string
      responses:
        200:
          description: Blob hash
          content:
            application/json:
              schema:
                type: object
                properties:
                  hash_type:
                    type: string
                  hexdigest:
                    type: string
      tags:
        - blob

  /api/v1/blob/{blobId}/visibility:
    put:
      summary: Set blob visibility
      parameters:
        - in: path
          name: blobId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                public:
                  type: boolean
      responses:
        204:
          description: Blob visibility updated successfully
      tags:
        - blob

  /api/v1/blob/{blobId}/acl:
    post:
      summary: Add ACL for a blob
      parameters:
        - in: path
          name: blobId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                allowed_users:
                  type: array
                  items:
                    type: string
      responses:
        204:
          description: ACL added successfully
      tags:
        - blob

    put:
      summary: Update ACL for a blob
      parameters:
        - in: path
          name: blobId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                allowed_users:
                  type: array
                  items:
                    type: string
      responses:
        204:
          description: ACL updated successfully
      tags:
        - blob

    get:
      summary: Get ACL for a blob
      parameters:
        - in: path
          name: blobId
          required: true
          schema:
            type: string
      responses:
        200:
          description: ACL retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  allowed_users:
                    type: array
                    items:
                      type: string
      tags:
        - blob

  /api/v1/blob/{blobId}/acl/{username}:
    delete:
      summary: Remove a specific user from blob ACL
      parameters:
        - in: path
          name: blobId
          required: true
          schema:
            type: string
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        204:
          description: User removed from ACL
      tags:
        - blob
